# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu2404" do |node|
    node.vm.box = "bento/ubuntu-24.04"

    node.vm.provider "virtualbox" do |v|
      v.linked_clone = true
    end

  end
end

# vi: set ft=ruby :
