# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu2004" do |node|
    node.vm.box = "ubuntu/focal64"

    node.vm.provider "virtualbox" do |v|
      v.linked_clone = true
    end

    node.vm.provision "shell",
      inline: "sudo sed -i 's/archive.ubuntu.com/free.nchc.org.tw/g' /etc/apt/sources.list"

    node.vm.provision "shell",
      inline: "sudo apt-get update && sudo apt-get install -y python-is-python3"

    # node.vm.provision "ansible" do |ansible|
    #   ansible.playbook = "provision.yml"
    #   ansible.become = true
    # end

  end
end

# vi: set ft=ruby :
