# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-10.2-STABLE"

  config.ssh.shell = "sh"

  config.vm.provision "shell", inline: <<-SHELL
    /usr/sbin/pkg install -y python27
    ln -s /usr/local/bin/python2.7 /usr/bin/python
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.become = true
    ansible.host_key_checking = "false"
  end
end

# vi: set ft=ruby :
