#!/usr/bin/env ansible-playbook
# vim:ft=ansible :
# ============================================================
#  Author: chusiang / chusiang.lai (at) gmail.com
#  Filename: upgrade-openssl.yml
#  Modified: 2016-03-03 11:44
#  Description: deploy Nginx + php5-fpm + MariaDB
#  Reference: 
#
#   1. ansible print debug msg variable - Server Fault
#    - http://serverfault.com/questions/695786/ansible-print-debug-msg-variable
#
# =========================================================== 

---

- name: deploy php5-fpm
  hosts: all
  sudo: True
  tasks:

    - name: install php5-fpm
      apt: name=php5-fpm update_cache=yes state=latest
      when: ansible_distribution == "Ubuntu"

    - name: install php5-mysql
      apt: name=php5-mysql update_cache=yes state=latest
      when: ansible_distribution == "Ubuntu"

    - name: check version on ubuntu
      command: dpkg-query -W php5-fpm
      register: dpkg_package_version
      when: ansible_distribution == "Ubuntu"

    - name: print version
      debug:
        msg: "php5-fpm Version: {{ dpkg_package_version.stdout }}"
      when: ansible_distribution == "Ubuntu"

    - name: add php.ini
      template: src=templates/php.ini.j2 dest=/etc/php5/fpm/php.ini
      notify:
        - restart php-fpm
      when: ansible_distribution == "Ubuntu"

    - name: check php-fpm process
      shell: ps aux | grep php-fpm | head -n 2
      register: check_php5fpm_process

    - name: print php-fpm process
      debug:
        msg: "{{ check_php5fpm_process.stdout }}"

  handlers:

    - name: restart php5-fpm
      service: name=php5-fpm state=restarted

- name: deploy nginx
  hosts: all
  sudo: True
  tasks:
  
    - name: install nginx
      apt: name=nginx update_cache=yes state=latest
      when: ansible_distribution == "Ubuntu"

    - name: check version on ubuntu
      command: dpkg-query -W nginx
      register: dpkg_package_version
      when: ansible_distribution == "Ubuntu"

    - name: print version
      debug:
        msg: "Nginx Version: {{ dpkg_package_version.stdout }}"
      when: ansible_distribution == "Ubuntu"

    - name: add vhost file
      template: src=templates/nginx/example.tw.j2 dest=/etc/nginx/sites-available/example.tw
      notify:
        - restart nginx
      when: ansible_distribution == "Ubuntu"

    - name: enable vhost
      file:
        src: /etc/nginx/sites-available/example.tw
        dest: /etc/nginx/sites-enabled/example.tw
        state: link
      when: ansible_distribution == "Ubuntu"

    - name: check nginx process
      shell: ps aux | grep nginx | head -n 2
      register: check_nginx_process

    - name: print nginx process
      debug:
        msg: "{{ check_nginx_process.stdout }}"

  handlers:

    - name: restart nginx
      service: name=nginx state=restarted

