#!/usr/bin/env ansible-playbook
# vim: ft=ansible :
# ============================================================
#  Author: chusiang / chusiang.lai@gmail.com
#  Filename: deploy-docker.yml
#  Modified: 2016-03-10 16:10
#  Description: deploy docker-engine.
# =========================================================== 

---
- name: deploy docker-engine
  hosts: all
  tasks:

    - name: add an apt key
      sudo: True
      apt_key:
        keyserver: hkp://p80.pool.sks-keyservers.net:80
        id: 58118E89F3A912897C070ADBF76221572C52609D

    - name: add apt repository
      sudo: True
      apt_repository:
        repo: 'deb https://apt.dockerproject.org/repo ubuntu-trusty main'
        state: present

    - name: install
      sudo: True
      apt:
        name: docker-engine
        update_cache: yes
        state: latest
        cache_valid_time: 3600

    - name: check version
      command: dpkg-query -W docker-engine
      register: dpkg_package_version

    - name: print version
      debug:
        msg: "Package Version: {{ dpkg_package_version.stdout }}"

