#!/usr/bin/env ansible-playbook
# ============================================================
#  Author: chusiang / chusiang.lai (at) gmail.com
#  Blog: http://note.drx.tw
#  Filename: dotfiles.yml
#  Modified: 2026-06-02 23:40
#  Description: Deploying my dotfiles and vimrc.
# ===========================================================

---
- name: Deploying my dotfiles and vimrc
  hosts: all
  tasks:

    - name: Check vim verison
      ansible.builtin.shell: vim --version | sed -n 1p
      register: vim_version
      changed_when: false

    - name: Print vim version
      ansible.builtin.debug:
        msg: "Vim Version: {{ vim_version.stdout }}"

    - name: Create workspace for verison control system
      file:
        path: ~/vcs
        state: directory

    - name: Get dotfiles
      git:
        repo: https://github.com/chusiang/tuxENV.git
        dest: ~/vcs/tuxENV

    - name: Deploy dotfiles
      shell: make install
      args:
        chdir: ~/vcs/tuxENV/
      ignore_errors: True

    - name: Get vimrc
      git:
        repo: https://github.com/chusiang/vimrc.git
        dest: ~/vcs/vimrc

    - name: Deploy vimrc
      shell: make install
      args:
        chdir: ~/vcs/vimrc/
      async: 60
      ignore_errors: True

# vim: set filetype=yaml.ansible
