#!/usr/bin/env ansible-playbook
# vim:ft=ansible :
# ============================================================
#  Author: chusiang / chusiang.lai (at) gmail.com
#  Filename: upgrade-git.yml
#  Modified: 2016-03-21 16:50
#  Description: security upgrade the git package
#  Reference: 
#
#   1. use `yum list` with ansible? need install 'yum-utils' package.
#   2. Git stable releases : "Ubuntu Git Maintainers" team
#    - https://launchpad.net/~git-core/+archive/ubuntu/ppa
#
# =========================================================== 

---
- name: upgrade package of git 
  hosts: all
  vars:
    code_name: trusty
  tasks:

    - name: add an apt repository on ubuntu
      sudo: True
      apt_repository: >
        repo='deb http://ppa.launchpad.net/git-core/ppa/ubuntu {{ code_name }} main'
        state=present
      when: ansible_distribution == "Ubuntu"

    - name: add an apt repository source on ubuntu
      sudo: True
      apt_repository: >
        repo='deb-src http://ppa.launchpad.net/git-core/ppa/ubuntu {{ code_name }} main'
        state=present
      when: ansible_distribution == "Ubuntu"

    - name: add an apt key
      sudo: True
      apt_key: >
        keyserver=keyserver.ubuntu.com
        id=E1DD270288B4E6030699E45FA1715D88E1DF1F24
      when: ansible_distribution == "Ubuntu"

    - name: upgrade on ubuntu
      sudo: True
      apt: name=git update_cache=yes state=latest
      when: ansible_distribution == "Ubuntu"

    - name: check version on ubuntu
      command: dpkg-query -W git
      register: dpkg_package_version
      when: ansible_distribution == "Ubuntu"

    - name: print version
      debug:
        msg: "Package Version: {{ dpkg_package_version.stdout }}"
      when: ansible_distribution == "Ubuntu"

    - name: upgrade on centos
      sudo: True
      yum: name=git update_cache=yes state=latest
      when: ansible_distribution == "CentOS"

    - name: check version on centos
      yum: list=git
      register: yum_package_list
      when: ansible_distribution == "CentOS"

    - name: print version
      debug:
        msg: "{{ yum_package_list.results.1.nevra }}"
      when: ansible_distribution == "CentOS"

    #- name: print list message
    #  debug:
    #    msg: "{{ yum_package_list }}"
    #  when: ansible_distribution == "CentOS"

