# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.ssh.insert_key = false

  # Managed node
  #
  config.vm.define :node1 do |node|
    node.vm.box = "bento/ubuntu-24.04"
    node.vm.hostname = "node1.local"

    node.vm.network "private_network", ip: "192.168.50.11"
    node.vm.network "forwarded_port", guest: 80, host: 8080
    node.vm.network "forwarded_port", guest: 443, host: 8443

    node.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end

    UBUNTU_SCRIPTS = [ "init-vagrant.sh", "install-vim.sh" ]
    for script_file in UBUNTU_SCRIPTS
      node.vm.provision "shell", path: script_file
    end

  end

  # Jupyter
  #
  config.vm.define :jupyter, primary: true do |jupyter|
    jupyter.vm.box = "bento/ubuntu-24.04"
    jupyter.vm.hostname = "jupyter.local"

    jupyter.vm.network "private_network", ip: "192.168.50.1"
    jupyter.vm.network "forwarded_port", guest: 8888, host: 8888

    jupyter.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end

    # install jupyter.
    JUPYTER_SCRIPTS = [ "init-vagrant.sh", "init-jupyter.sh", "install-vim.sh" ]
    for script_file in JUPYTER_SCRIPTS
      jupyter.vm.provision "shell", path: script_file
    end

    jupyter.vm.provision "shell", run: "always", inline: <<-SHELL
      ipython notebook --notebook-dir=/vagrant --no-browser --ip=0.0.0.0 &
    SHELL

    # install ansible.
    jupyter.vm.provision "shell", inline: <<-SHELL
      echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" | \
        sudo tee /etc/apt/sources.list.d/ansible.list
      echo "deb-src http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" | \
        sudo tee -a /etc/apt/sources.list.d/ansible.list
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 7BB9C367
      sudo apt-get update
      sudo apt-get install ansible
    SHELL

    # get ssh key.
    jupyter.vm.provision "shell", inline: <<-SHELL
      sudo cp /vagrant/.vagrant/machines/ubuntu1/virtualbox/private_key ~/.ssh/id_rsa
      sudo ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
    SHELL

    # add ssh-key to other node.
    jupyter.vm.provision "ansible" do |ansible|
      ansible.playbook = "ssh-addkey.yml"
      #ansible.sudo = true
      #ansible.verbose = "vvv"
    end
  end

end
